### ISSUE TITLE
RenderStatePackager release mode only m_PipelineType == -1

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#129] opened 2022-01-21 14:35 UTC
When using RenderStatePackager compiled in release mode, unpacking a PSO outputs the following error:

Diligent Engine: ERROR: Debug assertion failed in GetShaderTypeFromPipelineIndex(), file GraphicsAccessories.cpp, line 1633:
Unexpected pipeline type

Looking into the debugger, it turns out unpacked m_PipelineType == -1.

Using RenderStatePackager compiled in debug mode works fine.

**Comment by TheMostDiligent** [comment] 2022-01-23 05:11
There is a strong evidence that this issue is caused by the compiler bug in gcc9+ when using optimization levels O2 and above.
The issue should be fixed by https://github.com/DiligentGraphics/DiligentCore/commit/9a397c3a5cc0580f342acaabe906e753d7c828be

**Closed by TheMostDiligent** 2022-01-23 05:11 UTC
Labels: bug

**Comment by TheMostDiligent** [comment] 2022-01-23 07:09
Steps to reproduce:

1. Build the project using gcc9.3 with `-O2` compiler flag
2. Run RenderStatePackager with some json file that contains a graphics pipeline (use --vulkan flag)
3. Try to unpack the pipeline. The following helper test should be useful:

```cpp
TEST(ArchiveTest, CheckArchive)
{
    auto* pEnv             = TestingEnvironment::GetInstance();
    auto* pDevice          = pEnv->GetDevice();
    auto* pArchiverFactory = pEnv->GetArchiverFactory();
    auto* pDearchiver      = pDevice->GetEngineFactory()->GetDearchiver();

    if (!pDearchiver || !pArchiverFactory)
        GTEST_SKIP() << "Archiver library is not loaded";

    const auto CurrentDeviceFlag = static_cast<ARCHIVE_DEVICE_DATA_FLAGS>(1u << pDevice->GetDeviceInfo().Type);

    RefCntAutoPtr<IShaderSourceInputStreamFactory> pStreamFactory;
    pArchiverFactory->CreateDefaultShaderSourceStreamFactory(R"(path\to\archive)", &pStreamFactory);

    RefCntAutoPtr<IFileStream> pFileStream;
    pStreamFactory->CreateInputStream("archive.bin", &pFileStream);

    auto pFileData = DataBlobImpl::Create();
    pFileStream->ReadBlob(pFileData);

    auto pSource = ArchiveMemoryImpl::Create(pFileData);

    RefCntAutoPtr<IDeviceObjectArchive> pArchive;
    pDearchiver->CreateDeviceObjectArchive(pSource, &pArchive);

    {
        RefCntAutoPtr<IPipelineState> pPipeline;
        PipelineStateUnpackInfo       UnpackInfo{};
        UnpackInfo.pArchive     = pArchive;
        UnpackInfo.pDevice      = pDevice;
        UnpackInfo.PipelineType = PIPELINE_TYPE_GRAPHICS;
        UnpackInfo.Name         = "PSO1";
        pDearchiver->UnpackPipelineState(UnpackInfo, &pPipeline);
        ASSERT_NE(pPipeline, nullptr);
    }

    {
        RefCntAutoPtr<IPipelineState> pPipeline;
        PipelineStateUnpackInfo       UnpackInfo{};
        UnpackInfo.pArchive     = pArchive;
        UnpackInfo.pDevice      = pDevice;
        UnpackInfo.PipelineType = PIPELINE_TYPE_GRAPHICS;
        UnpackInfo.Name         ="PSO2";
        pDearchiver->UnpackPipelineState(UnpackInfo, &pPipeline);
        ASSERT_NE(pPipeline, nullptr);
    }
}
```

4. Observe that the test fails because `m_PipelineType` member of `PipelineResourceSignatureBase` is -1.
  It should be helpful to log the pipeline type [here](https://github.com/DiligentGraphics/DiligentCore/blob/00386acc43a0c3979e6bf48d988d486f9ec1f7ec/Graphics/GraphicsEngine/include/PipelineResourceSignatureBase.hpp#L386).
5. Build the same project using `-O1` compiler flag, repeat the test and observe that the pipeline type is valid
6. Compare archives produced by the archivers built with `-O1` and `-O2` and observe they are not identical
