### ISSUE TITLE
RenderStatePackager is not using multiple threads on MacOS

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#88] opened 2021-12-24 15:31 UTC
CPU usage of RenderStatePackager is around 10% with 90% of the CPU being idle when compiling multiple .json files on MacOS (--metal_ios).

**Comment by MikhailGorobets** [comment] 2021-12-24 15:39
What is stage of execution? Shader compilation or archive serialization?
Also try experimenting with the number of threads (argument `-t`)

**Comment by speedym** [comment] 2021-12-24 16:25
@MikhailGorobets I have sent a repro case via email as it is under NDA. I think only one instance of the metal tool is called at any given moment.

**Comment by speedym** [comment] 2022-01-19 10:06
I have just retested with the latest RenderStatePackager and I can confirm that this issue has not been fixed. The idle% when using top command line tool is 90%, and the average CPU usage is around 10%.

**Comment by TheMostDiligent** [comment] 2022-01-19 19:22
The packager starts the specified number of threads, and on MacOS it starts individual process to compile shaders in every thread. Our initial investigation showed that there is a bottleneck in GLSLang memory allocator.
We will investigate this issue further.

**Comment by TheMostDiligent** [comment] 2022-06-28 05:33
Apparently, this works OK on M1 MacBooks, so there might be some issue on Apple side.
@speedym closing this now, but feel free to reopen if the issue is still relevant.

**Closed by TheMostDiligent** 2022-06-28 05:33 UTC
Labels: wontfix
